import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " Product Catalog Viewer",
  description: " Product Catalog Viewer Generated by Next.js with auth mohamed hasan",
  icons: {
    icon: "/logo.svg",
  },
  keywords: ["products", "catalog", "shopping", "e-commerce", "next.js", "tailwindcss", "typescript", "react", "javascript"],
  authors: [{ name: "mohamed hasan", url: "https://mo7med.vercel.app/" }],
  creator: "mohamed hasan",
  publisher: "mohamed hasan",
  openGraph: {
    title: " Product Catalog Viewer",
    description: " Product Catalog Viewer Generated by Next.js with auth mohamed hasan",
    url: "https://mo7med.vercel.app/",
    siteName: " Product Catalog Viewer",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
